before_script:
  - pip install tox setuptools
cache:
  paths:
  - /root/.cache
stages:
  - style
  - test
  - package

py33:
  stage: test
  image: python:3.3
  script:
    - tox -e py33

py34:
  stage: test
  image: python:3.4
  script:
    - tox -e py34

py35:
  stage: test
  image: python:3.5
  script:
    - tox -e py35

flake8:
  image: python:latest
  stage: style
  script:
    - tox -e flake8

isort:
  image: python:latest
  stage: style
  script:
    - tox -e isort

wheel:
  image: python:3.5
  stage: package
  script:
    tox -e wheel
  artifacts:
    paths:
      - dist/

sdist:
  image: python:3.5
  stage: package
  script:
    tox -e sdist
  artifacts:
    paths:
      - dist/
